# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfIhXjH4sGwLhSXrBwQus6NZ04EgZ66_
"""

import cv2

for i in range(1, 6):
    rasm = cv2.imread(f"{i}_oqqora.jpg")
    rangli_rasm = cv2.applyColorMap(rasm, cv2.COLORMAP_HOT)
    cv2.imwrite(f"{i}_rangli.jpg", rangli_rasm)